---
- hosts: localhost
  name: Provision SMB Share on ONTAP
  gather_facts: false
  collections:
    - netapp.ontap

  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
      use_rest: auto

  vars:
    netapp_hostname:  192.168.0.101
    netapp_username:  admin
    svm_name:         "ntap-svm01-nas"
    aggr_name:        "cluster1_01_aggr01"
    volume_name:      "demo_smb_vol_03"
    junction_path:    "/{{ volume_name }}"
    size:             1
    size_unit:        gb            # Defaults to 'gd'
    security_style:   unix          # Defaults to 'unix'

    autosize_mode:    grow_shrink   # Defaults to off
    # size_change_threshold: 0        # Defaults to 10%
    # grow_threshold_percent: 99      # Defaults to 85 - 98% (depending on voume size)
    # increment_size:   50m  
    # maximum_size:     10g           # 20% greater than vol size when set
    # minimum_size:     21m           # vol size when set
    # shrink_threshold_percent: 40    # Defaults to 50%
    
    share_name:       "{{ volume_name }}"
    set_acls:         true          # Controls file security task (ACLs)
    share_acls:
      - { state: "absent", target: "Everyone", ace: "full_control" }
      - { state: "present", target: "Domain Admins", ace: "full_control" }
      - { state: "present", target: "Domain Users", ace: "change" }
    file_acls:
      - state: present
        user: "Domain Admins"
        access: "access_allow"
        propagation_mode: "replace"
        advanced_rights:
          full_control: true
      - state: present
        user: "Domain Users"
        access: "access_allow"
        propagation_mode: "propagate"
        advanced_rights:
          full_control: false
          read_data: true
          append_data: true
          write_data: true
  
  vars_prompt:
    - name: "netapp_password"
      prompt: "Enter the NetApp Admin Password"
      private: yes

  tasks:
    - name: Create NTFS volume for SMB
      netapp.ontap.na_ontap_volume:
        state:                      "{{ state                   | default('present') }}"
        vserver:                    "{{ svm_name }}"
        name:                       "{{ volume_name }}"
        aggregate_name:             "{{ aggr_name }}"
        size:                       "{{ size }}"
        size_unit:                  "{{ size_unit               | default(omit) }}"
        junction_path:              "{{ junction_path           | default(omit) }}"
        volume_security_style:      "{{ security_style          | default(omit) }}"
        user_id:                    "{{ user_id                 | default(omit) }}"
        group_id:                   "{{ group_id                | default(omit) }}"
        unix_permissions:           "{{ unix_permissions        | default(omit) }}"
        space_guarantee:            "{{ space_guarantee         | default(omit) }}"
        snapshot_policy:            "{{ snapshot_policy         | default(omit) }}"
        percent_snapshot_space:     "{{ percent_snapshot_space  | default(omit) }}"
        tiering_policy:             "{{ tiering_policy          | default(omit) }}"
        export_policy:              "{{ export_policy           | default(omit) }}"
        qos_adaptive_policy_group:  "{{ adaptive_qos            | default(omit) }}"
        qos_policy_group:           "{{ qos                     | default(omit) }}"
        logical_space_reporting:    "{{ logical_space_reporting | default(omit) }}"
        wait_for_completion:        "{{ wait_for_completion     | default(omit) }}"

    - name: Set volume autosize
      netapp.ontap.na_ontap_volume_autosize:
        vserver:                    "{{ svm_name }}"
        volume:                     "{{ volume_name }}"
        mode:                       "{{ autosize_mode }}"
        grow_threshold_percent:     "{{ grow_threshold_percent  | default(omit) }}"
        increment_size:             "{{ increment_size          | default(omit) }}"
        maximum_size:               "{{ maximum_size            | default(omit) }}"
        minimum_size:               "{{ minimum_size            | default(omit) }}"
        shrink_threshold_percent:   "{{ shrink_threshold_percent | default(omit) }}"
      when: autosize_mode is defined

    - name: Create SMB share
      netapp.ontap.na_ontap_cifs:
        state: present
        name: "{{ share_name }}"
        path: "{{ junction_path }}"
        vserver: "{{ svm_name }}"
        browsable: true
        oplocks: true
        show_snapshot: true
        comment: "Demo SMB share provisioned by Ansible"

    - name: Manages SMB share ACLs
      netapp.ontap.na_ontap_cifs_acl:
        state: "{{ item.state }}"
        share_name: "{{ share_name }}"
        vserver: "{{ svm_name }}"
        user_or_group: "{{ item.target }}"
        permission: "{{ item.ace }}"
      loop: "{{ share_acls }}"
    
    - name: Replace Default ACLs with Authenticated Users
      netapp.ontap.na_ontap_file_security_permissions_acl:
        state: "{{ item.state }}"
        vserver: "{{ svm_name }}"
        access_control: file_directory
        path: "{{ junction_path }}"
        validate_changes: warn
        propagation_mode: "{{ item.propagation_mode }}"
        access: "{{ item.access }}"
        acl_user: "{{ item.user }}"
        apply_to:
          this_folder: true
        advanced_rights: "{{ item.advanced_rights }}"
      loop: "{{ file_acls }}"
      when: set_acls is true
