---
- hosts: localhost
  name: Provision SMB Share on ONTAP
  gather_facts: false
  collections:
    - netapp.ontap

  module_defaults:
    group/netapp.ontap.netapp_ontap:
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
      use_rest: auto

  vars:
    netapp_hostname: 192.168.0.101
    netapp_username: admin
    svm_name: "ntap-svm01-nas"
    aggr_name: "cluster1_01_aggr01"
    volume_name: "demo_vol3"
    volume_size: "1"
    size_unit: "gb"
    share_name: "{{ volume_name }}"
    junction_path: "/{{ volume_name }}"
    security_style: ntfs
    set_acls:   true
    share_acls:
      - { state: "absent", target: "Everyone", ace: "full_control" }
      - { state: "present", target: "Domain Admins", ace: "full_control" }
      - { state: "present", target: "Domain Users", ace: "change" }
    file_acls:
      - state: present
        user: "Domain Admins"
        access: "access_allow"
        propagation_mode: "replace"
        advanced_rights:
          full_control: true
      - state: present
        user: "Domain Users"
        access: "access_allow"
        propagation_mode: "propagate"
        advanced_rights:
          full_control: false
          read_data: true
          append_data: true
          write_data: true
  vars_prompt:
    - name: "netapp_password"
      prompt: "Enter the NetApp Admin Password"
      private: yes

  tasks:
    - name: Create volume
      netapp.ontap.na_ontap_volume:
        state: present
        vserver: "{{ svm_name }}"
        aggregate_name: "{{ aggr_name }}"
        name: "{{ volume_name }}"
        size: "{{ volume_size }}"
        size_unit: "{{ size_unit }}"
        junction_path: "{{ junction_path }}"
        volume_security_style: "{{ security_style | default(omit) }}"
        space_guarantee: none

    - name: Create SMB share
      netapp.ontap.na_ontap_cifs:
        state: present
        name: "{{ share_name }}"
        path: "{{ junction_path }}"
        vserver: "{{ svm_name }}"
        browsable: true
        oplocks: true
        show_snapshot: true
        comment: "Demo SMB share provisioned by Ansible"

    - name: Manage SMB share ACLs
      netapp.ontap.na_ontap_cifs_acl:
        state: "{{ item.state }}"
        share_name: "{{ share_name }}"
        vserver: "{{ svm_name }}"
        user_or_group: "{{ item.target }}"
        permission: "{{ item.ace }}"
      loop: "{{ share_acls }}"
    
    - name: Replace Default ACLs with Authenticated Users
      netapp.ontap.na_ontap_file_security_permissions_acl:
        state: "{{ item.state }}"
        vserver: "{{ svm_name }}"
        access_control: file_directory
        path: "{{ junction_path }}"
        validate_changes: warn
        propagation_mode: "{{ item.propagation_mode }}"
        access: "{{ item.access }}"
        acl_user: "{{ item.user }}"
        apply_to:
          this_folder: true
        advanced_rights: "{{ item.advanced_rights }}"
      loop: "{{ file_acls }}"
      when: set_acls is true
